name: api_fcm
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.0.0
  dio: ^4.0.6
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  # oauth2: ^2.0.1
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  dotenv: ^4.0.1
  # googleapis: ^9.2.0

dev_dependencies:
  lints: ^2.0.0
  strict: ^1.4.0
  test: ^1.15.0
